version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: infoviz
      MB_DB_PASS: infoviz
      MB_DB_HOST: host.docker.internal
